spring:
  application:
    name: lanchonete
  datasource:
    url: jdbc:postgresql://localhost:5433/lanchonete_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:seu_usuario}
    password: ${MAIL_PASSWORD:sua_senha}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    livereload:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

app:
  mail:
    provider: ${APP_MAIL_PROVIDER:mailtrap}
